name: Build & Test CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
      - name: Build packages
        run: yarn build
      - name: Automated Tests
        run: yarn test
      - name: Visual regression test
        env:
          CHROMATIC_KEY: ${{ secrets.CHROMATIC_KEY }}
        run: yarn test:chromatic
